# Generated by Django 4.1.7 on 2023-03-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_postblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='contenuto',
            field=models.TextField(max_length=150),
        ),
    ]
