# Generated by Django 4.1.7 on 2023-03-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_postblog_contenuto'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='postblog',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
