# Generated by Django 4.1.7 on 2023-03-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_postblog_data_postblog_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='contenuto',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
