# Generated by Django 4.1.7 on 2023-03-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_postblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
