# Generated by Django 4.1.7 on 2023-03-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_postblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
